### ISSUE TITLE
ajax to pull html tables on 3 seconds refresh interval

### ISSUE THREAD

**Issue by janfilips** [jparicka/cryptodice2.win#15]
fuck tables you'll make two ajax calls which both returns generated html tables

the result on the ajax call is html not json and we'll display this html on the web as is

/ajax/games/mine requires a parameter player_session_id (I have this generated on the index.html template for you)

**Comment by HonzaKirchner** [comment]
V te metode kde tu tabulku generujes dej section tagu id="my_games".. Tomuhle tagu pak kazde tri vteriny nastavuju ten novy obsah.

**Comment by jparicka** [comment]
Ok, tak jsem to trochu predelal.
Prosim, kdyz udelas GET na /ajax/games dostanes vygenerovanu html tabulku All games.
Kdyz udelas POST na /ajax/games a posles tam "wallet" tak to zobrazi My games
Diky!
