### ISSUE TITLE
need html input for metamask warnings and also make the warning a little bit wider

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#18]
See, in some warnings I have text-picture-text on the others it's picture-text-text
I need to define these warnings as html individually (right now it's handled in a quite generic way)
Can you please check?

<img width="400" alt="screenshot 2018-12-31 at 15 27 52" src="https://user-images.githubusercontent.com/870699/50562076-12a63b80-0d11-11e9-958b-af3edd33a90f.png">

<img width="354" alt="screenshot 2018-12-31 at 15 28 32" src="https://user-images.githubusercontent.com/870699/50562077-12a63b80-0d11-11e9-9aa4-b165af255d3a.png">

<img width="411" alt="screenshot 2018-12-31 at 15 28 48" src="https://user-images.githubusercontent.com/870699/50562078-12a63b80-0d11-11e9-84d4-981a01628740.png">

**Comment by HonzaKirchner** [comment]
Dodej HTML pro kazdou hlasku a ja to tam pridam.

**Comment by jparicka** [comment]
Oni jsou tam (v tych screenshotoch) - jenom obrazek presunout tam kde je "xxx-move-picture-above"
