### ISSUE TITLE
default bet is 0.15 and it jumps straight to 0.01 in firefox right after (-) is pressed

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#24]

**Comment by HonzaKirchner** [comment]
Stahnul jsem Firefox a funguje to u me jak ma

**Comment by jparicka** [comment]
nope

**Comment by jparicka** [comment]
<img width="651" alt="screenshot 2019-01-02 at 14 40 43" src="https://user-images.githubusercontent.com/870699/50594323-685b1f00-0e9c-11e9-8b2d-fe572909b67a.png">

**Comment by jparicka** [comment]
je to na 0.15, kliknem 1x minus tlacitko a skoci na 0.01 :-/
zatim na to kasli ale v kazdem pripade je tam ten problem...

**Comment by jparicka** [comment]
Video - 
[firefox.mov.zip](https://github.com/jparicka/cryptodice2.win/files/2726939/firefox.mov.zip)

**Comment by jparicka** [comment]
ale asi bych na to sral....
co myslis ty?

**Comment by jparicka** [comment]
out of scope
