### ISSUE TITLE
fortgot to apply metamask warning messages titles

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#25]

**Comment by jparicka** [comment]
upravim tam trochu este ten content - ale, .. titles nejsou reflektovane na popupu

<img width="843" alt="screenshot 2019-01-04 at 13 37 12" src="https://user-images.githubusercontent.com/870699/50688470-e565d000-1025-11e9-8eeb-7aa163b5862e.png">

**Comment by HonzaKirchner** [comment]
Fixed
