### ISSUE TITLE
maybe a message saying loading games would do nicely here thank you

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#29]
<img width="398" alt="screenshot 2019-01-04 at 21 16 06" src="https://user-images.githubusercontent.com/870699/50708840-fe8e7100-1065-11e9-819a-7153364bb5d5.png">

**Comment by HonzaKirchner** [comment]
Jako mozna bych dal jinej loader.. Nebo uz tabulku bez dat s loaderem ale nejakou message bych tam nedaval - to pusobi zastarale :D

**Comment by jparicka** [comment]
out of scope
