### ISSUE TITLE
hyperlink notifications

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#30]
<img width="1003" alt="screenshot 2019-01-04 at 21 18 43" src="https://user-images.githubusercontent.com/870699/50708934-562cdc80-1066-11e9-8009-fab1d8999d34.png">

**Comment by jparicka** [comment]
maybe white color hyperlinks not blue

**Comment by HonzaKirchner** [comment]
bily to bejt nemuze.. Musis to odlisit aby bylo znat ze se na to da kliknout. Takze se vyber jestli jinou barvu (a kdyztak jakou) a nebo jestli to nechat
