### ISSUE TITLE
distinguish "playerLost" notification type (somewhat red but not too red in color)

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#32]

**Comment by jparicka** [comment]
<img width="978" alt="screenshot 2019-01-05 at 19 03 47" src="https://user-images.githubusercontent.com/870699/50727544-a9f9fd00-111c-11e9-9d0c-755f06f97715.png">

💯

**Comment by HonzaKirchner** [comment]
Udelejme to takhle.. Jak posilas ty vitezny notifikace tak to posilas neco jako:
congratulations, your transaction <a href="..." >1387462983</a> ....

Zacni to ale cele posilat obalene do divu tak, aby to vypadalo takhle:

<div class="notifText">Your transaction <a href=http://ropsten.etherscan.io/tx/'+transactionHash+' target="_blank"> <font color="#C0C0C0">'+transactionHash+'</font></a> was recorded on the network..</div>'

S tim ze vitezne notifikace posilej jako:
<div class="notifText winNotif"> ... </div>
A prohrane notifikace jako: 
<div class="notifText lostNotif"> ... </div>

**Comment by jparicka** [comment]
co kdybych proste vratil json s hodnotama notification_type a notification_text
notif_types: player_wins / player_loses

**Comment by HonzaKirchner** [comment]
Radsi to html prosim jenom s rozdilnou classou.. Takhle je to temer ready s json-em bych to musel predelavat

**Comment by jparicka** [comment]
OK, Honzo, tohle tak nejak fungovalo - akurat ze to nedela presne to co bych chtel :-/

Vybarvilo to background pod textem - my chcem vybarvovat cely ten notif..

<img width="1035" alt="screenshot 2019-01-11 at 17 50 11" src="https://user-images.githubusercontent.com/870699/51047740-8413a300-15c9-11e9-97e5-56bdb335cf29.png">

Can you please check?

**Comment by jparicka** [comment]
thank you!
