### ISSUE TITLE
investigate metamask warning message on the browser console

### ISSUE THREAD

**Issue by jparicka** [jparicka/cryptodice2.win#37]
ATTENTION: In an effort to improve user privacy, MetaMask stopped exposing user accounts to dapps if "privacy mode" is enabled on November 2nd, 2018. Dapps should now call provider.enable() in order to view and use accounts. Please see https://bit.ly/2QQHXvF for complete information and up-to-date example code.
(anonymous) @ inpage.js:1

**Comment by HonzaKirchner** [comment]
V objektu metamaskErrors pribyla moznost private.. Tak si tam dopln content co chces zobrazit

**Comment by jparicka** [comment]
Content v zmyslu napriklad ze rollDice?

**Comment by HonzaKirchner** [comment]
nene:
        private: {
          title: 'Metamask private',
          content: "<div><img id=\"popup-error-image\" src=\"/static/images/metamask-main-network.png\"></img><br/><br/>Oops, you're on the wrong network.<br/><br/>Simply open Metamask and switch over to Main Ethereum Network.</br><br/></br></div>",
          popupWidth: -1
        },

Tak jako u ostatnich metamask hlasek - porste obrazek a popis

**Comment by jparicka** [comment]
moved this up to the new issue #40
